#!/usr/bin/env bash

set -e

URL=$(echo "$QUTE_URL" | awk -F/ '{print $3}' | sed 's/www.//g')
echo "message-info 'Looking for password for $URL...'" > $QUTE_FIFO

TOKEN=$(echo -n $(security find-generic-password -s "1Password" -w) | op signin --output=raw)
UUID_URL=$(op list items --session="$TOKEN" | jq -r '.[] | "\(.uuid):\(.overview.url)"' | grep "$URL")

IFS=: read -r UUID var2 <<< "$UUID_URL"
ITEM=$(op get item --session="$TOKEN" "$UUID")

PASSWORD=$(echo "$ITEM" | jq -r '.details.fields | .[] | select(.designation=="password") | .value')

if [ -n "$PASSWORD" ]; then
  TITLE=$(echo "$ITEM" | jq -r '.overview.title')
  USERNAME=$(echo "$ITEM" | jq -r '.details.fields | .[] | select(.designation=="username") | .value')
  echo "$PASSWORD" | pbcopy
  echo "$TITLE password in clipboard; Username is $USERNAME" | terminal-notifier -title "Qutebrowser 1Password" -sound default
  TOTP=$(echo "$ITEM" | op get totp --session="$TOKEN" "$UUID")
  if [ -n "$TOTP" ]; then
    sleep 5s
    echo "$TOTP" | pbcopy
    echo "One time password for $TITLE: $TOTP" | terminal-notifier -title "Qutebrowser 1Password" -sound default
  fi
else
  echo "No password found for $URL" | terminal-notifier -title "Qutebrowser 1Password" -sound default
fi
