#!/usr/bin/env bash

set -e

BOOKMARKS_PATH="${QUTE_CONFIG_DIR}/bookmarks/urls"
echo "$BOOKMARKS_PATH"
if [[ -f "$BOOKMARKS_PATH" ]]; then
  rm "$BOOKMARKS_PATH"
  touch "$BOOKMARKS_PATH"
fi

AM_I_WORKING=$(sh ~/Desktop/bookmarks.sh)
TAGS=
if [[ $AM_I_WORKING -eq "true" ]]; then
  TAGS="favourites + work"
else
  TAGS="favourites + personal"
fi
BOOKMARKS=$(buku --nostdin -t $TAGS --json)
echo $BOOKMARKS
echo $BOOKMARKS | jq -r '.[] | "\(.uri)\t\t\(.title)"' > "$QUTE_CONFIG_DIR/bookmarks/urls"

sh "$QUTE_DATA_DIR"/userscripts/reload-quickmarks

